name: ğŸš€ Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ğŸ” Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 138.68.170.93
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/react-CI-CD-Docker
            echo "ğŸ“¥ Pulling latest main branch..."
            git reset --hard
            git clean -fd
            git pull origin main

            echo "ğŸ§¹ Stopping containers and removing volumes..."
            docker compose down --volumes

            echo "ğŸ”¨ Rebuilding containers..."
            docker compose up --build -d

            echo "âœ… Production deployed: http://<ip>"
